version: 2
jobs:
  test:
    working_directory: ~/app
    parallelism: 1
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.7.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "Gemfile.lock" }}
            - v1-dep-bundle-
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: v1-dep-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: ruby ./sorting-hat.rb
workflows:
  version: 2
  build:
    jobs:
      - test
